// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNhnL4GBDbk5n1Nu5RWq_lsbaxzZ5LbjQ',
    appId: '1:609923213326:web:086426670973e84939345f',
    messagingSenderId: '609923213326',
    projectId: 'portfolio-48e21',
    authDomain: 'portfolio-48e21.firebaseapp.com',
    storageBucket: 'portfolio-48e21.appspot.com',
    measurementId: 'G-EL1XFCFJBM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4GjGKEi-Lk9hG2jMBc9BJpTnMGaIPUJA',
    appId: '1:609923213326:android:204f5fc52e9a37e639345f',
    messagingSenderId: '609923213326',
    projectId: 'portfolio-48e21',
    storageBucket: 'portfolio-48e21.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDC9I42HZLGclUKXJrtX69-Ozx7ReKWzGs',
    appId: '1:609923213326:ios:1a50c95a8d48a12639345f',
    messagingSenderId: '609923213326',
    projectId: 'portfolio-48e21',
    storageBucket: 'portfolio-48e21.appspot.com',
    iosClientId: '609923213326-eptnvs5718uukqvl0l5afdmvusj3d4mt.apps.googleusercontent.com',
    iosBundleId: 'com.example.videoEditorPorfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDC9I42HZLGclUKXJrtX69-Ozx7ReKWzGs',
    appId: '1:609923213326:ios:1a50c95a8d48a12639345f',
    messagingSenderId: '609923213326',
    projectId: 'portfolio-48e21',
    storageBucket: 'portfolio-48e21.appspot.com',
    iosClientId: '609923213326-eptnvs5718uukqvl0l5afdmvusj3d4mt.apps.googleusercontent.com',
    iosBundleId: 'com.example.videoEditorPorfolio',
  );
}
